import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";

const myFont = localFont({
  src: [
    {
      path: '../fonts/sukhumvit-set/SukhumvitSet-Bold.ttf',
      weight: '700',
      style: 'bold',
    },
    {
      path: '../fonts/sukhumvit-set/SukhumvitSet-Light.ttf',
      weight: '300',
      style: 'light',
    },
    {
      path: '../fonts/sukhumvit-set/SukhumvitSet-Medium.ttf',
      weight: '500',
      style: 'medium',
    },
    {
      path: '../fonts/sukhumvit-set/SukhumvitSet-SemiBold.ttf',
      weight: '600',
      style: 'semibold',
    },
    {
      path: '../fonts/sukhumvit-set/SukhumvitSet-Text.ttf',
      weight: '400',
      style: 'text',
    },
    {
      path: '../fonts/sukhumvit-set/SukhumvitSet-Thin.ttf',
      weight: '100',
      style: 'thin',
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
